# Config Template

dataset: ML20M
log_name: EDLAE_b_geq_0_diag0_L2const
save_dir: ./saved_model/ML20M/EDLAE_b_geq_0_diag0_L2const/strong_generalization
log_dir: ./saved_log/ML20M/EDLAE_b_geq_0_diag0_L2const/strong_generalization

needs_train: False
pre_process: 'strong_generalization'

hyper_params:
    a: [1.0]
    b: [0.1, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0]
    p: [0.1, 0.25, 0.5, 0.75]
    L2const: [10.0, 70.0, 100.0, 300.0, 500.0]


dataset_config:
    leave_out:
        ML20M:
            train: ../data/processed_data/leave_out/ML20M/train.csv
            valid: ../data/processed_data/leave_out/ML20M/valid.csv
            test: ../data/processed_data/leave_out/ML20M/test.csv
            sid: ../data/processed_data/leave_out/ML20M/unique_sid.txt

    strong_generalization:
        ML20M:
            train: ../data/processed_data/strong_generalization/ML20M/train.csv
            valid_tr: ../data/processed_data/strong_generalization/ML20M/validation_tr.csv
            valid_te: ../data/processed_data/strong_generalization/ML20M/validation_te.csv
            test_tr: ../data/processed_data/strong_generalization/ML20M/test_tr.csv
            test_te: ../data/processed_data/strong_generalization/ML20M/test_te.csv
            sid: ../data/processed_data/strong_generalization/ML20M/unique_sid.txt
    